# Generated by Django 4.1.7 on 2023-05-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiapp', '0012_alter_booking_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
